dist: trusty
sudo: required
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
before_script:
  - sudo apt-get update
  - sudo apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm config set strict-ssl false
  - sudo npm install -g ionic cordova
  - sudo npm install --unsafe-perm=true --allow-root
script:
  - ionic cordova build android
