dist: trusty
sudo: required
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - npm config set strict-ssl false
  - npm install -g ionic cordova
  - npm install
script:
  - ionic cordova build android
